main: old1.o poly.o
	g++ $? -o $@

# oldpoly.out: old1.cc poly.cc func.h
# 	g++ -g func.h old1.cc poly.cc -o oldpoly.out
# newpoly.out: new1.cc newpoly.cc func.h
# 	g++ -g func.h new1.cc newpoly.cc -o newpoly.out
# oldposy.out: old2.cc posy.cc func.h
# 	g++ -g func.h old2.cc posy.cc -o oldposy.out
# newposy.out: new2.cc newposy.cc func.h
# 	g++ -g func.h old2.cc posy.cc -o oldposy.out

