oldpoly.out: old1.o poly.o func.h
    g++ -g func.h old1.o poly.o -o oldpoly.out
newpoly.out: new1.o newpoly.o func.h
    g++ -g func.h new1.o newpoly.o -o newpoly.out
oldposy.out: old2.o posy.o func.h
    g++ -g func.h old2.o posy.o -o oldposy.out


