main.out:main.o reviewer_assigner.o reviewer_assigner.h 
	g++ -g main.o reviewer_assigner.o reviewer_assigner.h -o main.out
reviewer_assigner.o:reviewer_assigner.cc reviewer_assigner.h
	g++ -g -c reviewer_assigner.cc -o reviewer_assigner.o
main.o:main.cc
	g++ -g -c main.cc -o main.o











